[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.4.1"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/xitongsys/parquet-go"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btcd"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btcutil"

[[constraint]]
  branch = "master"
  name = "github.com/syndtr/goleveldb"
